apiVersion: apps/v1
kind: Depolyment
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev
  namespace: devnamespace
  annotations:
    myecrimage: 934192905905.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchExpressions:
      - key: web
        operator: In
        values:
          - yellowapp-pods
      - key: env
        operator: NotIn
        values:
          - dev
      - key: fortend
        operator: Exists
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: podlevellabels
      labels:
        web: yellowapp-pods
        env: prod
        fortend: web
    spec:
      containers:
        - name: yellowapp
          image: krishna731/mycssimages:glass
          ports:
            - name: yellowapp-ports
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
            path: "/manu"
            port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          redinessProbe:
            exec:
              command:
                - echo Hi, How are you ?
            resources:
              requests:
                cpu: "100m"    
                memory: "200Mi"
              limits:
                cpu: "300m"  .
                memory: "300Mi"   