apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev
  namespace: devnamespace
  annotations:
    kubernetes.io/change-cause: "glass-application"
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchLabels:
      app: my-css
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-css
        name: css-pod
    spec:
      containers:
        - name: css-con
          image: krishna731/mycssimages:glass
          ports:
            - containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "200m"
              memory: "150Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"
